baseURL = "https://thawing-tor-36976.herokuapp.com/"
LanguageCode = "en-us"
title = "Amin Tahmasbi"
theme = "hugo-now-ui"
publishDir="myapp/templates"

enableGitInfo = true
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
disableKinds = ["taxonomy", "taxonomyTerm", "sitemap"]

# [permalinks]
    # post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "#about"
    pre = "<i class='fas fa-info'></i>"
    weight = 1

[[menu.main]]
    name = "Experience"
    url = "#experience"
    pre = "<i class='far fa-building'></i>"
    weight = 2

[[menu.main]]
    name = "Education"
    url = "#education"
    pre = "<i class='fas fa-graduation-cap'></i>"
    weight = 3

[[menu.main]]
    name = "Skills"
    url = "#skills"
    pre = "<i class='fas fa-code'></i>"
    weight = 4


# [[menu.main]]
#     name = "Dropdown"
#     pre = "<i class='now-ui-icons ui-1_settings-gear-63'></i>"
#     url = "#"
#     weight = 5
#     identifier = "dropdown"

[[menu.main]]
    name = "Projects"
    url = "#projects"
    pre = "<i class='fas fa-project-diagram'></i>"
    weight = 5
    # parent = "dropdown"

[[menu.main]]
    name = "Publications"
    url = "#publications"
    pre = "<i class='fas fa-book-open'></i>"
    weight = 6
    # parent = "dropdown"

[[menu.main]]
        name = "Contact"
        url = "#contact"
        pre = "<i class='fas fa-paper-plane'></i>"
        weight = 7
        # parent = "dropdown"

# [[menu.main]]
#       name = "GitHub"
#       weight = 8
#       pre = "<i class='fab fa-github'></i>"
#       identifier = "github"
#       post = "external"
#       url = "https://github.com/amintahmasbi"


# [[menu.main]]
#     name = "Template"
#     pre = "<i class='now-ui-icons files_paper'></i>"
#     url = "/template/"
#     weight = 1
#     parent = "dropdown"
# [[menu.main]]
#     name = "Posts"
#     pre = "<i class='now-ui-icons ui-1_calendar-60'></i>"
#     url = "/post/"
#     weight = 2
#     parent = "dropdown"


[[menu.contact]]
    identifier = "twitter"
    pre = "<i class='fab fa-twitter'></i>"
    url = "https://twitter.com/amin_tahmasbi"
    post = "Follow me"
    weight = 4

[[menu.contact]]
    identifier = "github"
    pre = "<i class='fab fa-github'></i>"
    url = "https://github.com/amintahmasbi"
    post = "My Github"
    weight = 2

[[menu.contact]]
    identifier = "linkedin"
    pre = "<i class='fab fa-linkedin'></i>"
    url = "https://www.linkedin.com/in/amin-tahmasbi"
    post = "Connect"
    weight = 3

[[menu.contact]]
    identifier = "resume"
    pre = "<i class='now-ui-icons education_paper'></i>"
    url = "https://tahmasbi.net/resume.pdf"
    post = "Download Resume"
    weight = 1


[[menu.footer]]
    identifier = "copyright"
    name = "MIT"
    pre = "<i class='fa fa-balance-scale'></i>"
    url = "https://mit-license.org/"
    weight = 1


[params]
    AuthorName = "Amin Tahmasbi"
    background = "/img/Florida_bay.jpg" #"/img/Yellowstone_gayser.jpg"
    # tint = "black" # Only orange
    custom_css = ["css/highlight.min.css"]
    custom_js = []
    # date_format = "Wed, Dec 10, 2018"
    description = "My personal website <br> Proudly created with Hugo and Bootstrap 4"

    # options for highlight.js (version, additional languages, and theme)
    highlight_version = "9.13.1"
    highlight_languages = ["bash", "cpp", "cmake", "dockerfile", "json", "python"]
    highlight_style = "github" #doesn't work!
